#!/bin/bash
if [ -d "/var/www/apply.interninit.com" ]; then
    rm -rf /var/www/apply.interninit.com/*
    rm -rf /var/www/apply.interninit.com/.[a-zA-Z_]*
fi

if [ -d "/home/ubuntu/FLASKAPPS/backend" ]; then
    rm -rf /home/ubuntu/FLASKAPPS/backend/*
    rm -rf /home/ubuntu/FLASKAPPS/backend/.[a-zA-Z_]*
fi

if [ -d "/var/www/html" ]; then
    rm -r /var/www/html/*
    rm -r /var/www/html/.[a-zA-Z_]*
fi