/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cc446411-480b-403d-a645-6db83e20c727",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3jQ8qJ99t",
    "aws_user_pools_web_client_id": "2ica3btn4lg5qd63bdjgh0v77",
    "oauth": {}
};


export default awsmobile;
