/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f5f57de8-06cf-4367-b011-1205a4609d05",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BxVk6strD",
    "aws_user_pools_web_client_id": "3ae4dbjivjdgkukd6593dsad2t",
    "oauth": {}
};


export default awsmobile;
